#!/bin/bash

./testproj $DATADIR/alaska/data23 < $DATADIR/alaska/parm23 > testfile
./testproj $DATADIR/alaska/data23a < $DATADIR/alaska/parm23a >> testfile
./testproj $DATADIR/alaska/data23b < $DATADIR/alaska/parm23b >> testfile

for f in cmp*
do
    grep -qi "Differences exist" $f && exit 1
done

exit 0
